import os, errno, re
import logging

log = logging.getLogger('gitosis.ssh')

_ACCEPTABLE_USER_RE = re.compile(r'^[a-zA-Z][a-zA-Z0-9_.-]*(@[a-zA-Z][a-zA-Z0-9.-]*)?$')

def isSafeUsername(user):
    match = _ACCEPTABLE_USER_RE.match(user)
    return (match is not None)

def readKeys(keydir, userprefix="", scanSubdirs=True, prependPath=False):
    """
    Read SSH public keys from ``keydir/*.pub`` and from its dubdirectories
    """
    for filename in os.listdir(keydir):
        if filename.startswith('.'):
            continue
        basename, ext = os.path.splitext(filename)
        path = os.path.join(keydir, filename)
        if os.path.isfile(path):
            if ext != '.pub':
                continue

            username = userprefix+basename
            if not isSafeUsername(username):
                log.warn('Unsafe SSH username in keyfile: %r', path)
                continue

            f = file(path)
            for line in f:
                line = line.rstrip('\n')
                yield (username, line)
            f.close()
        elif os.path.isdir(path) and scanSubdirs:
            # scan subdirectory
            newprefix = userprefix
            # we use the path as a prefix, so a file called keydir/users/max.pub
            # yields the username users-max
            if prependPath:
                newprefix = filename+"-"+userprefix
            for v in readKeys(path, newprefix, scanSubdirs, prependPath):
                yield v


COMMENT = '### autogenerated by gitosis, DO NOT EDIT'

def generateAuthorizedKeys(keys):
    TEMPLATE=('command="gitosis-serve %(user)s",no-port-forwarding,'
              +'no-X11-forwarding,no-agent-forwarding,no-pty %(key)s')

    yield COMMENT
    for (user, key) in keys:
        yield TEMPLATE % dict(user=user, key=key)

_COMMAND_RE = re.compile('^command="(/[^ "]+/)?gitosis-serve [^"]+",no-port-forw'
                         +'arding,no-X11-forwarding,no-agent-forwardi'
                         +'ng,no-pty .*')

def filterAuthorizedKeys(fp):
    """
    Read lines from ``fp``, filter out autogenerated ones.

    Note removes newlines.
    """

    for line in fp:
        line = line.rstrip('\n')
        if line == COMMENT:
            continue
        if _COMMAND_RE.match(line):
            continue
        yield line

def writeAuthorizedKeys(path, keydir, config):
    tmp = '%s.%d.tmp' % (path, os.getpid())
    try:
        in_ = file(path)
    except IOError, e:
        if e.errno == errno.ENOENT:
            in_ = None
        else:
            raise

    try:
        out = file(tmp, 'w')
        try:
            if in_ is not None:
                for line in filterAuthorizedKeys(in_):
                    print >>out, line
            
            # retrieve keys from subdirectories?
            subdirs = config.getboolean("gitosis", "keysubdirs")
            # prepend the sub-path to username?
            prepend = config.getboolean("gitosis", "prependpath")
            keygen = readKeys(keydir, userprefix="", scanSubdirs=subdirs, prependPath=prepend)
            for line in generateAuthorizedKeys(keygen):
                print >>out, line

            os.fsync(out)
        finally:
            out.close()
    finally:
        if in_ is not None:
            in_.close()
    os.rename(tmp, path)
